name: Build and Run SRBMiner Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t srbminer .

      - name: Run Docker Container
        run: |
          # Run the container in detached mode and map port 80 in the container to 8080 on the host
          docker run -d -p 8080:80 --name srbminer_container srbminer

      - name: List Running Containers
        run: docker ps
